# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='ScreenName',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='favorites_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='ident',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='profile_background_color',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='profile_background_image_url',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='profile_banner_url',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='profile_image_url',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='profile_link_color',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='profile_sidebar_fill_color',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='profile_text_color',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='protected',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='status_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='url',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='utc_offset',
        ),
    ]
