# Generated by Django 2.0.2 on 2018-05-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_delete_usermention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='event',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
