# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20171205_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
