# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_auto_20171205_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=60)),
                ('ident', models.IntegerField(default=0)),
                ('result', models.FloatField(default=0)),
            ],
        ),
    ]
