# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('metrics', models.FloatField(default=0)),
            ],
        ),
    ]
