# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_intel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intel',
            old_name='metrics',
            new_name='metric',
        ),
    ]
